package interpreter;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 27/5/20 20:37 from the specification file
 * <tt>file:/C:/Users/pablo/eclipse-workspace/PL20_p2/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\6\1\0"+
    "\1\4\2\0\1\33\1\20\1\47\1\50\1\45\1\15\1\44\1\7"+
    "\1\12\1\46\1\11\11\13\1\42\1\41\1\5\1\43\1\10\2\0"+
    "\1\26\1\36\1\17\1\32\1\14\1\25\2\21\1\40\2\21\1\27"+
    "\1\37\1\31\1\34\2\21\1\23\1\30\1\22\1\24\2\21\1\16"+
    "\2\21\4\0\1\21\1\0\1\26\1\36\1\17\1\32\1\14\1\25"+
    "\2\21\1\40\2\21\1\27\1\37\1\31\1\34\2\21\1\23\1\30"+
    "\1\22\1\24\2\21\1\16\2\21\1\51\1\35\1\52\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    43,    86,   129,    86,   172,   215,    86,    86,   258, 
      301,    86,   344,   387,    86,   430,   473,   516,   559,   602, 
      645,   688,   731,   774,    86,   817,    86,   860,   903,    86, 
      946,   989,    86,    86,    86,    86,    86,    86,    86,   172, 
     1032,    86,    86,  1075,  1118,  1161,  1204,  1247,  1290,  1333, 
     1376,  1419,  1462,  1505,  1548,  1591,  1634,  1677,  1720,   430, 
     1763,  1806,    86,    86,  1849,  1161,  1118,  1892,  1935,    86, 
     1978,  2021,  2064,  2107,  2150,  2193,   430,  2236,  2279,   430, 
     2322,  2365,  2408,  2451,  2494,  2537,   430,  2580,   430,  2623, 
     2666,  2709,  2752,   430,  2795,  2838,  2881,  2924,  2967,  3010, 
     3053,  3096,   430,  3139,  3182,  3225,  3268,  3311,   430,  3354, 
     3397,   430,  3440,  3483,   430,  3526,  3569,  3612,  3655,   430, 
     3698,  3741,  3784,   430,   430,  3827,   430,   430,  3870,  3913, 
      430
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\20\1\23\1\24\1\20\1\25\1\26\1\20\1\27"+
    "\1\30\1\20\1\31\1\32\1\33\1\34\1\35\1\20"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\53\3\55\0\1\5\50\0\1\50\1\4"+
    "\1\5\50\50\6\0\1\51\34\0\1\52\52\0\1\53"+
    "\20\0\1\54\1\55\1\54\2\0\1\56\45\0\1\15"+
    "\1\55\1\15\1\57\47\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\10\20\1\60\1\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\12\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\5\20\1\61\4\20\1\0"+
    "\1\20\1\0\3\20\12\0\53\62\11\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\2\20\1\63\7\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\1\20\1\64"+
    "\1\0\2\20\1\0\12\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\3\20"+
    "\1\65\1\20\1\66\4\20\1\0\1\20\1\0\2\20"+
    "\1\67\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\10\20\1\70\1\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\1\20\1\71"+
    "\10\20\1\0\1\20\1\0\2\20\1\72\23\0\1\20"+
    "\1\0\2\20\1\0\2\20\1\0\12\20\1\0\1\73"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\2\20\1\74\7\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\12\20"+
    "\1\0\1\75\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\12\20\1\0\1\20\1\0\2\20"+
    "\1\76\55\0\1\77\52\0\1\100\16\0\1\101\54\0"+
    "\1\54\1\55\1\54\50\0\1\55\1\0\1\55\50\0"+
    "\1\102\1\0\2\102\2\0\1\102\5\0\2\102\3\0"+
    "\1\102\3\0\1\102\25\0\1\55\1\0\1\55\1\0"+
    "\1\103\2\0\1\103\43\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\1\20\1\104\10\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\2\20\1\105\7\20\1\0\1\20\1\0\3\20\32\0"+
    "\1\106\43\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\3\20\1\107\6\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\1\20\1\110"+
    "\3\20\1\111\4\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\10\20\1\112"+
    "\1\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\6\20\1\113\3\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\10\20\1\114\1\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\11\20\1\115\1\0\1\20\1\0\3\20\23\0\1\20"+
    "\1\0\2\20\1\0\2\20\1\0\2\20\1\116\7\20"+
    "\1\0\1\20\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\10\20\1\117\1\20\1\0\1\20"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\1\20\1\120\10\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\12\20"+
    "\1\0\1\121\1\0\3\20\23\0\1\20\1\0\1\20"+
    "\1\122\1\0\2\20\1\0\12\20\1\0\1\20\1\0"+
    "\3\20\21\0\1\123\54\0\1\20\1\0\1\20\1\124"+
    "\1\0\2\20\1\0\12\20\1\0\1\125\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\5\20"+
    "\1\126\4\20\1\0\1\20\1\0\3\20\23\0\1\20"+
    "\1\0\1\20\1\127\1\0\2\20\1\0\12\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\3\20\1\130\6\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\6\20\1\131\3\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\1\20\1\132\1\0\12\20"+
    "\1\0\1\20\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\7\20\1\107\2\20\1\0\1\20"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\7\20\1\133\2\20\1\0\1\20\1\0\1\20"+
    "\1\134\1\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\3\20\1\135\6\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\12\20"+
    "\1\0\1\136\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\6\20\1\137\3\20\1\0\1\20"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\10\20\1\140\1\20\1\0\1\20\1\0\3\20"+
    "\12\0\7\123\1\141\43\123\11\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\2\20\1\142\7\20\1\0\1\20"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\10\20\1\143\1\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\1\20\1\144\1\0"+
    "\12\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\2\20\1\145\7\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\12\20\1\0\1\20\1\0\2\20\1\146"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\12\20"+
    "\1\0\1\20\1\0\2\20\1\147\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\12\20\1\0\1\20\1\0"+
    "\2\20\1\150\23\0\1\20\1\0\2\20\1\0\1\20"+
    "\1\151\1\0\12\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\1\20\1\152\1\0\2\20\1\0\12\20"+
    "\1\0\1\20\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\1\20\1\153\10\20\1\0\1\20"+
    "\1\0\3\20\12\0\7\123\1\154\43\123\11\0\1\20"+
    "\1\0\2\20\1\0\2\20\1\0\12\20\1\0\1\155"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\1\20"+
    "\1\156\1\0\12\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\1\20\1\157"+
    "\10\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\10\20\1\160\1\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\12\20\1\0\1\161\1\0\3\20\23\0"+
    "\1\20\1\0\1\20\1\162\1\0\2\20\1\0\12\20"+
    "\1\0\1\20\1\0\3\20\23\0\1\20\1\0\2\20"+
    "\1\0\2\20\1\0\1\20\1\163\10\20\1\0\1\20"+
    "\1\0\3\20\23\0\1\20\1\0\2\20\1\0\2\20"+
    "\1\0\5\20\1\164\4\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\2\20\1\0\2\20\1\0\2\20"+
    "\1\165\7\20\1\0\1\20\1\0\3\20\12\0\7\123"+
    "\1\154\1\5\42\123\11\0\1\20\1\0\1\20\1\166"+
    "\1\0\2\20\1\0\12\20\1\0\1\20\1\0\3\20"+
    "\23\0\1\20\1\0\1\20\1\167\1\0\2\20\1\0"+
    "\12\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\10\20\1\170\1\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\10\20\1\171\1\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\10\20\1\172\1\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\5\20\1\173"+
    "\4\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\7\20\1\174\2\20\1\0"+
    "\1\20\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\2\20\1\175\7\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\1\20\1\176\10\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\12\20\1\0"+
    "\1\177\1\0\3\20\23\0\1\20\1\0\2\20\1\0"+
    "\2\20\1\0\7\20\1\200\2\20\1\0\1\20\1\0"+
    "\3\20\23\0\1\20\1\0\2\20\1\0\2\20\1\0"+
    "\2\20\1\201\7\20\1\0\1\20\1\0\3\20\23\0"+
    "\1\20\1\0\2\20\1\0\2\20\1\0\5\20\1\202"+
    "\4\20\1\0\1\20\1\0\3\20\23\0\1\20\1\0"+
    "\2\20\1\0\2\20\1\0\7\20\1\203\2\20\1\0"+
    "\1\20\1\0\3\20\12\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  9,  9,  1,  1,  9,  1,  1,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  9,  1,  1,  9,  1,  1, 
     9,  9,  9,  9,  9,  9,  9,  0,  0,  9,  9,  1,  1,  0,  0,  1, 
     1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9, 
     0,  1,  0,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	

    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3956];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 10: 
        case 12: 
        case 43: 
          {  return symbolFactory.newSymbol( "ENTERO", ENTERO, Integer.parseInt(yytext()) );		 }
        case 132: break;
        case 69: 
          {  return symbolFactory.newSymbol( "CHAR", CHAR, (char)yytext().charAt(1) );				 }
        case 133: break;
        case 65: 
          {  return symbolFactory.newSymbol( "ENTERO", ENTERO, Integer.decode(yytext()) );			 }
        case 134: break;
        case 86: 
          {  return symbolFactory.newSymbol( "BOOLEAN", BOOLEAN, Boolean.parseBoolean(yytext()) );	 }
        case 135: break;
        case 6: 
          {  return symbolFactory.newSymbol("LESSER", LESSER);			 }
        case 136: break;
        case 62: 
          {  return symbolFactory.newSymbol("ASSIGN", ASSIGN); 	 }
        case 137: break;
        case 111: 
          {  return symbolFactory.newSymbol("RETORNO", RETORNO);	 }
        case 138: break;
        case 33: 
          {  return symbolFactory.newSymbol("MULT", MULT);			 }
        case 139: break;
        case 32: 
          {  return symbolFactory.newSymbol("COMA", COMA);			 }
        case 140: break;
        case 29: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);			 }
        case 141: break;
        case 14: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);			 }
        case 142: break;
        case 2: 
        case 5: 
        case 17: 
        case 30: 
        case 31: 
          {  emit_warning("Unrecognized character '" +yytext()+"' -- ignored");  }
        case 143: break;
        case 126: 
          {  return symbolFactory.newSymbol("DCLBOOL", DCLBOOL);		 }
        case 144: break;
        case 124: 
          {  return symbolFactory.newSymbol("DCLCHAR", DCLCHAR);		 }
        case 145: break;
        case 35: 
          {  return symbolFactory.newSymbol("IZQPAREN", IZQPAREN);	 }
        case 146: break;
        case 9: 
          {  return symbolFactory.newSymbol("GREATER", GREATER);		 }
        case 147: break;
        case 36: 
          {  return symbolFactory.newSymbol("DERPAREN", DERPAREN);	 }
        case 148: break;
        case 37: 
          {  return symbolFactory.newSymbol("IZQLLAVE", IZQLLAVE);	 }
        case 149: break;
        case 38: 
          {  return symbolFactory.newSymbol("DERLLAVE", DERLLAVE);	 }
        case 150: break;
        case 63: 
          {  return symbolFactory.newSymbol("EQUALTO", EQUALTO);		 }
        case 151: break;
        case 88: 
          {  return symbolFactory.newSymbol("DCLREAL", DCLREAL);		 }
        case 152: break;
        case 13: 
        case 15: 
        case 16: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 25: 
        case 27: 
        case 28: 
        case 47: 
        case 48: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 58: 
        case 60: 
        case 61: 
        case 67: 
        case 68: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 77: 
        case 78: 
        case 80: 
        case 81: 
        case 83: 
        case 84: 
        case 85: 
        case 87: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 94: 
        case 95: 
        case 97: 
        case 98: 
        case 99: 
        case 100: 
        case 101: 
        case 103: 
        case 104: 
        case 105: 
        case 106: 
        case 109: 
        case 110: 
        case 112: 
        case 113: 
        case 115: 
        case 116: 
        case 117: 
        case 118: 
        case 120: 
        case 121: 
        case 122: 
        case 125: 
        case 128: 
        case 129: 
          {  return symbolFactory.newSymbol("IDENT", IDENT, yytext());		 }
        case 153: break;
        case 34: 
          {  return symbolFactory.newSymbol("DIV", DIV);			 }
        case 154: break;
        case 26: 
        case 59: 
          {  return symbolFactory.newSymbol("OR", OR);				 }
        case 155: break;
        case 24: 
        case 76: 
          {  return symbolFactory.newSymbol("AND", AND);			 }
        case 156: break;
        case 7: 
        case 79: 
          {  return symbolFactory.newSymbol("NOT", NOT);			 }
        case 157: break;
        case 11: 
          {  return symbolFactory.newSymbol("DOT", DOT);			 }
        case 158: break;
        case 57: 
          {  return symbolFactory.newSymbol("IF", IF);					 }
        case 159: break;
        case 130: 
          {  return symbolFactory.newSymbol("ENDWHILE", ENDWHILE);		 }
        case 160: break;
        case 41: 
          {  return symbolFactory.newSymbol("LESSEREQ", LESSEREQ);		 }
        case 161: break;
        case 42: 
          {  return symbolFactory.newSymbol("GREATEREQ", GREATEREQ);	 }
        case 162: break;
        case 108: 
          {  return symbolFactory.newSymbol("DCLENTERO", DCLENTERO);	 }
        case 163: break;
        case 114: 
          {  return symbolFactory.newSymbol("DCLSTRUCT", DCLSTRUCT);	 }
        case 164: break;
        case 127: 
          {  return symbolFactory.newSymbol("WHILE", WHILE);			 }
        case 165: break;
        case 123: 
          {  return symbolFactory.newSymbol("THEN", THEN);				 }
        case 166: break;
        case 119: 
          {  return symbolFactory.newSymbol("FUNC", FUNC);				 }
        case 167: break;
        case 8: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);		 }
        case 168: break;
        case 93: 
          {  return symbolFactory.newSymbol("ELSE", ELSE);				 }
        case 169: break;
        case 102: 
          {  return symbolFactory.newSymbol("ENDIF", ENDIF);			 }
        case 170: break;
        case 3: 
        case 4: 
          { 								 }
        case 171: break;
        case 44: 
          {  return symbolFactory.newSymbol( "FP", FP, Float.parseFloat(yytext()) );  				 }
        case 172: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
