
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package interpreter;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DCLCHAR = 33;
  public static final int MULT = 13;
  public static final int CHAR = 38;
  public static final int ENTERO = 35;
  public static final int GREATER = 18;
  public static final int SEMI = 2;
  public static final int MINUS = 11;
  public static final int NOT = 14;
  public static final int AND = 16;
  public static final int FP = 36;
  public static final int DCLSTRUCT = 34;
  public static final int DCLBOOL = 32;
  public static final int EQUALTO = 17;
  public static final int OR = 15;
  public static final int DIV = 12;
  public static final int LESSER = 20;
  public static final int PLUS = 10;
  public static final int ASSIGN = 3;
  public static final int IF = 22;
  public static final int DOT = 8;
  public static final int RETORNO = 29;
  public static final int ENDWHILE = 27;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int DCLENTERO = 30;
  public static final int IDENT = 39;
  public static final int DCLREAL = 31;
  public static final int IZQPAREN = 4;
  public static final int LESSEREQ = 21;
  public static final int ENDIF = 25;
  public static final int ELSE = 24;
  public static final int FUNC = 28;
  public static final int DERPAREN = 5;
  public static final int WHILE = 26;
  public static final int THEN = 23;
  public static final int IZQLLAVE = 6;
  public static final int GREATEREQ = 19;
  public static final int DERLLAVE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "ASSIGN",
  "IZQPAREN",
  "DERPAREN",
  "IZQLLAVE",
  "DERLLAVE",
  "DOT",
  "COMA",
  "PLUS",
  "MINUS",
  "DIV",
  "MULT",
  "NOT",
  "OR",
  "AND",
  "EQUALTO",
  "GREATER",
  "GREATEREQ",
  "LESSER",
  "LESSEREQ",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "ENDWHILE",
  "FUNC",
  "RETORNO",
  "DCLENTERO",
  "DCLREAL",
  "DCLBOOL",
  "DCLCHAR",
  "DCLSTRUCT",
  "ENTERO",
  "FP",
  "BOOLEAN",
  "CHAR",
  "IDENT"
  };
}

